# Generated by Django 3.1.3 on 2020-11-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.IntegerField()),
                ('session_id', models.IntegerField()),
                ('code', models.CharField(max_length=40)),
                ('newreq', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UssdApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.IntegerField()),
                ('session_id', models.IntegerField()),
                ('code', models.CharField(max_length=40)),
                ('newreq', models.CharField(max_length=40)),
            ],
        ),
    ]
